# Week 2 - Preprocessing - Part 2
Keshia-Lee Martin<br>
OMDS-ModB2<br>
Media and Entertainment<br>

Datasets: <br>
[Movielens](https://grouplens.org/datasets/movielens/latest/), [Dataset Details](https://files.grouplens.org/datasets/movielens/ml-latest-small-README.html)<br>
[Movies Box office Dataset (2000-2024)](https://www.kaggle.com/datasets/aditya126/movies-box-office-dataset-2000-2024)

# Weekly graph question

The Storytelling With Data book mentions planning on a "Who, What, and How" for your data story.  Write down a possible Who, What, and How for your data, using the ideas in the book.

# Homework 2

In [122]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

## Movielens Dataset

This dataset describes 5-star rating and free-text tagging activity from MovieLens, a movie recommendation service. It contains 100836 ratings and 3683 tag applications across 9742 movies.

In [123]:
# creating DataFrames/variables for each csv file to understand the data in each file before combining
df_movie_links = pd.read_csv("movielens-links.csv")

df_movie_links.info()
print()
df_movie_links.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

             movieId        imdbId         tmdbId
count    9742.000000  9.742000e+03    9734.000000
mean    42200.353623  6.771839e+05   55162.123793
std     52160.494854  1.107228e+06   93653.481487
min         1.000000  4.170000e+02       2.000000
25%      3248.250000  9.518075e+04    9665.500000
50%      7300.000000  1.672605e+05   16529.000000
75%     76232.000000  8.055685e+05   44205.750000
max    193609.000000  8.391976e+06  525662.000000

In [124]:
df_movie_names = pd.read_csv("movielens-movies.csv")

df_movie_names.info()
print()
df_movie_names.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [125]:
# movie ratings by users
df_movie_ratings = pd.read_csv("movielens-ratings.csv")

df_movie_ratings.info()
print()
df_movie_ratings.describe() 
# based on data, need to check if the movieids are unique in the dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [126]:
# users tags of the movies
df_movie_tags = pd.read_csv("movielens-tags.csv")

df_movie_tags.info()
print()
df_movie_tags.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB

            userId        movieId     timestamp
count  3683.000000    3683.000000  3.683000e+03
mean    431.149335   27252.013576  1.320032e+09
std     158.472553   43490.558803  1.721025e+08
min       2.000000       1.000000  1.137179e+09
25%     424.000000    1262.500000  1.137521e+09
50%     474.000000    4454.000000  1.269833e+09
75%     477.000000   39263.000000  1.498457e+09
max     610.000000  193565.000000  1.537099e+09

In [127]:
# combining the movie links csv and the movie titles csvs first
links_name_merged = df_movie_links.merge(df_movie_names, on='movieId', how='outer')
links_name_merged.head()

,movieId,imdbId,tmdbId,title,genres
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,113497,8844.0,Jumanji (1995),Adventure|Children|Fantasy
2,3,113228,15602.0,Grumpier Old Men (1995),Comedy|Romance
3,4,114885,31357.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,113041,11862.0,Father of the Bride Part II (1995),Comedy

In [128]:
# combined the ratings csv with the the movie tags csv
ratings_tags_merged = df_movie_ratings.merge(df_movie_tags, on='movieId', how='outer')
ratings_tags_merged.sample(5)

,userId_x,movieId,rating,timestamp_x,userId_y,tag,timestamp_y
84289,124.0,318,4.5,1.336413e+09,474.0,Stephen King,1.137181e+09
207013,473.0,4878,4.0,1.169352e+09,567.0,hallucinatory,1.525283e+09
247743,249.0,51540,4.5,1.347888e+09,NaN,NaN,NaN
152307,294.0,2088,1.0,9.665968e+08,NaN,NaN,NaN
86863,82.0,356,4.5,1.084468e+09,474.0,Vietnam,1.137376e+09

In [129]:
# merged previous combined csvs together
df_merge_movies = links_name_merged.merge(ratings_tags_merged, on='movieId', how='outer')
df_merge_movies.sample(5)

,movieId,imdbId,tmdbId,title,genres,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
122715,1196,80684,1891.0,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,265.0,5.0,9.653148e+08,477.0,classic,1.262796e+09
72114,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,462.0,2.5,1.123891e+09,424.0,Tarantino,1.457845e+09
69342,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,427.0,4.5,1.053071e+09,599.0,original,1.498456e+09
181640,3005,145681,9481.0,"Bone Collector, The (1999)",Thriller,249.0,4.0,1.356439e+09,NaN,NaN,NaN
80231,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,583.0,4.0,1.481474e+09,599.0,smart writing,1.498457e+09

Based on the html details about the data, the timestamps represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970. There is no needs for this for our data. The timestamp columns need to be dropped.

In [130]:
df_merge_movies = df_merge_movies.drop('timestamp_x', axis=1)
df_merge_movies = df_merge_movies.drop('timestamp_y', axis=1)

Renaming columns userid_x and userid_y to know that which id is for the rating and which user is for the tagging of the movie.

In [136]:
df_merge_movies = df_merge_movies.rename(columns={'userId_x':'userId_rating'})
df_merge_movies = df_merge_movies.rename(columns={'userId_y':'userId_tag'})

Now, verifying that the columns were dropped and the columns were renamed.

In [137]:
df_merge_movies.head(50)

,movieId,imdbId,tmdbId,title,genres,userId_rating,rating,userId_tag,tag
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,336.0,pixar
1,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,474.0,pixar
2,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,567.0,fun
3,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,336.0,pixar
4,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,474.0,pixar
5,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,567.0,fun
6,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,336.0,pixar
7,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,474.0,pixar
8,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,567.0,fun
9,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,336.0,pixar
10,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,474.0,pixar
11,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,567.0,fun
12,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,336.0,pixar
13,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,474.0,pixar
14,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,567.0,fun
15,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.5,336.0,pixar
16,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.5,474.0,pixar
17,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.5,567.0,fun
18,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,4.0,336.0,pixar
19,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,4.0,474.0,pixar
20,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,4.0,567.0,fun
21,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21.0,3.5,336.0,pixar
22,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21.0,3.5,474.0,pixar
23,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21.0,3.5,567.0,fun
24,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27.0,3.0,336.0,pixar
25,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27.0,3.0,474.0,pixar
26,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27.0,3.0,567.0,fun
27,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31.0,5.0,336.0,pixar
28,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31.0,5.0,474.0,pixar
29,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31.0,5.0,567.0,fun
30,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32.0,3.0,336.0,pixar
31,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32.0,3.0,474.0,pixar
32,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32.0,3.0,567.0,fun
33,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33.0,3.0,336.0,pixar
34,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33.0,3.0,474.0,pixar
35,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33.0,3.0,567.0,fun
36,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40.0,5.0,336.0,pixar
37,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40.0,5.0,474.0,pixar
38,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40.0,5.0,567.0,fun
39,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,5.0,336.0,pixar
40,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,5.0,474.0,pixar
41,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,5.0,567.0,fun
42,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44.0,3.0,336.0,pixar
43,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44.0,3.0,474.0,pixar
44,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44.0,3.0,567.0,fun
45,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45.0,4.0,336.0,pixar
46,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45.0,4.0,474.0,pixar
47,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45.0,4.0,567.0,fun
48,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46.0,5.0,336.0,pixar
49,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46.0,5.0,474.0,pixar

The following steps, there will be checking for duplicate rows, missing or null values.

In [139]:
df_merge_movies.info()
print()
df_merge_movies.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285783 entries, 0 to 285782
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   movieId        285783 non-null  int64
 1   imdbId         285783 non-null  int64
 2   tmdbId         285770 non-null  float64
 3   title          285783 non-null  object
 4   genres         285783 non-null  object
 5   userId_rating  285762 non-null  float64
 6   rating         285762 non-null  float64
 7   userId_tag     233234 non-null  float64
 8   tag            233234 non-null  object
dtypes: float64(4), int64(2), object(3)
memory usage: 19.6+ MB

,movieId,imdbId,tmdbId,userId_rating,rating,userId_tag
count,285783.000000,2.857830e+05,285770.000000,285762.000000,285762.000000,233234.000000
mean,14927.663741,2.956050e+05,12797.315320,313.894279,3.841270,470.681354
std,31402.673519,5.150156e+05,43479.255523,179.451387,1.020798,153.324249
min,1.000000,4.170000e+02,2.000000,1.000000,0.500000,2.000000
25%,296.000000,1.098300e+05,489.000000,160.000000,3.000000,424.000000
50%,1721.000000,1.125730e+05,680.000000,314.000000,4.000000,477.000000
75%,5673.000000,2.415270e+05,8963.000000,465.000000,4.500000,599.000000
max,193609.000000,8.391976e+06,525662.000000,610.000000,5.000000,610.000000

This week, you will do the same types of exercises as last week, but you should use your chosen datasets that someone in your class found last semester. (They likely will not be the particular datasets that you found yourself.)

### Here are some types of analysis you can do  Use Google, documentation, and ChatGPT to help you:

- Summarize the datasets using info() and describe()

- Are there any duplicate rows?

- Are there any duplicate values in a given column (when this would be inappropriate?)

- What are the mean, median, and mode of each column?

- Are there any missing or null values?

    - Do you want to fill in the missing value with a mean value?  A value of your choice?  Remove that row?

- Identify any other inconsistent data (e.g. someone seems to be taking an action before they are born.)

- Encode any categorical variables (e.g. with one-hot encoding.)

### Conclusions:

- Are the data usable?  If not, find some new data!

- Do you need to modify or correct the data in some way?

- Is there any class imbalance?  (Categories that have many more items than other categories).

# 4. Storytelling With Data graph

Just like last week: choose any graph in the Introduction of Storytelling With Data (p. 1-17). Use matplotlib to reproduce it in a rough way. I don't expect you to spend an enormous amount of time on this; I understand that you likely will not have time to re-create every feature of the graph. However, if you're excited about learning to use matplotlib, this is a good way to do that. You don't have to duplicate the exact values on the graph; just the same rough shape will be enough.  If you don't feel comfortable using matplotlib yet, do the best you can and write down what you tried or what Google searches you did to find the answers.