# Week 2 - Preprocessing - Part 2
Keshia-Lee Martin<br>
OMDS-ModB2<br>
Media and Entertainment<br>

Datasets: <br>
[4 Services Streaming Movies and Tv](https://www.kaggle.com/datasets/sc0v1n0/4-services-streaming-movies-and-tv/data)<br>
[Movie Box Office Dataset (2000-2024)](https://www.kaggle.com/datasets/aditya126/movies-box-office-dataset-2000-2024)

# Weekly graph question

The Storytelling With Data book mentions planning on a "Who, What, and How" for your data story.  Write down a possible Who, What, and How for your data, using the ideas in the book.

<b>WHO:</b> This data can speak to those who care about what users are watching:
- Producers and studio heads who are looking at the success of movies by genre by the ratings of the various movies
- Business decision makers who are looking at which streaming services to place future tv and movies onto specific platforms
- Streaming platforms who can look at the other service platforms and compare what content they have versus others, also using the user ratings to add more of the higher rated works to their platforms.


<b>WHAT:</b> After looking at this data, the WHO can see:
- The engagement across specific movies, genres, and movie tags
- Any potential audience demand or improvements
- Where there are opportunities (more of a specific genre, year of release, etc.)
- Based on the streaming platforms, the pros and cons of that tv show or movie being on that platform. For example, Disney is mainly known for content for kids and with the combination of Hulu and ESPN+, have begun to include additional content. How is kid friendly content doing on the other platforms?


<b>HOW:</b> The two data sets together provide:
- Movielens - ratings, movie tags, and genres (dropped from analysis after cleaning the data)
- 4 Services Streaming - release year, year added to platform, genres, runtime, number of seasons
- Movie Box Office - revenue worldwide, domestic, and international, ratings, votes, and production country

# Homework 2

In [81]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

## Streaming Movies and TV Dataset

The 4 Services Streaming Movies and TV dataset adds a platform and content-distribution perspective through metadata on films and television content available across Netflix, Hulu, Prime Video, and Disney+, including genre, release year, age rating, and IMDb scores linked to streaming platform strategy and audience accessibility.

In [82]:
# creating df for each csv
df_streaming = pd.read_csv("all_streaming.csv")
df_streaming_genre = pd.read_csv("all_genre.csv")
# pd.reset_option('display.max_rows')
# df_streaming
# df_streaming_genre

In [83]:
# combining the data sets
df_movie_tv_streaming = df_streaming.join(df_streaming_genre)
df_movie_tv_streaming

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,"November 26, 2021",2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,0,0,0,0,0,0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,"November 26, 2021",1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,0,0,0,0,0,0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,0,0,0,0,0,0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,"November 26, 2021",2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,0,0,0,0,0,0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,"November 25, 2021",2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaN,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,0,0,0,0,0,0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaN,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,0,0,0,0,0,0
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaN,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,0,0,0,0,0,0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaN,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,0,0,0,0,0,0
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaN,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,0,0,0,0,0,0

In [84]:
# getting info and descriptive statistics
df_movie_tv_streaming.info()
df_movie_tv_streaming.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Columns: 122 entries, movie_or_serie to melodrama
dtypes: int64(112), object(10)
memory usage: 21.4+ MB

,release_year,Unnamed: 0,action,actionadventure,adult,adventure,animals,animation,anime,anthology,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
count,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,...,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000,22998.000000
mean,2010.811244,0.002609,0.140838,0.019654,0.005392,0.080094,0.009044,0.048961,0.028698,0.001217,...,0.000261,0.000174,0.000043,0.000130,0.000087,0.000130,0.000391,0.000087,0.000043,0.000087
std,15.401142,0.051012,0.347862,0.138811,0.073232,0.271444,0.094672,0.215791,0.166960,0.034872,...,0.016150,0.013187,0.006594,0.011421,0.009325,0.011421,0.019779,0.009325,0.006594,0.009325
min,1920.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2010.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2016.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2019.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2021.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [85]:
# checking if there are any movie duplicates under title
df_movie_tv_streaming['title'].is_unique

False

In [86]:
# show the duplicates
df_movie_tv_streaming[df_movie_tv_streaming['title'].duplicated(keep=False)]

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,0,0,0,0,0,0
12,Movie,The Pixar Story,Leslie Iwerks,"Stacy Keach, John Lasseter, Brad Bird, John Mu...",United States,"November 19, 2021",2007,91 min,documentary>family,A groundbreaking company forever changes the f...,...,0,0,0,0,0,0,0,0,0,0
58,TV Show,PJ Masks,uninformed director,"Kyle Breitkopf, Jacob Ursomarzo, Addison Holley","France, United Kingdom","October 20, 2021",2015,5 Seasons,actionadventure>animation>kids,Look out Night Time Baddies the PJ Masks are c...,...,0,0,0,0,0,0,0,0,0,0
74,Movie,Black Widow,Cate Shortland,"Scarlett Johansson, Florence Pugh, David Harbo...",United States,"October 6, 2021",2021,135 min,actionadventure>science>fiction>spyespionage,Natasha confronts her history as a spy and the...,...,0,0,0,0,0,1,0,0,0,0
89,TV Show,Rolie Polie Olie,uninformed director,"Cole Caplan, Kristen Bone, Robert Smith, Cathe...","Canada, United States, France","September 29, 2021",1998,5 Seasons,animation>science>fiction,Rolie Polie Olie’s life and adventures center ...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22950,Movie,The Rocky Horror Picture Show,Jim Sharman,"Richard O'Brien, Tim Curry, Patricia Quinn, Su...",uninformed country,NaN,1975,99 min,arts>entertainment>culture>comedy>science>fiction,"Part campy musical, part horror film, the movi...",...,0,0,0,0,0,0,0,0,0,0
22953,Movie,The Princess Bride,Rob Reiner,"Cary Elwes, Mandy Patinkin, Chris Sarandon, Ch...",uninformed country,NaN,1987,98 min,action>kids>science>fiction,Based on William Goldman's novel of the same n...,...,0,0,0,0,0,0,0,0,0,0
22979,Movie,Jack,Francis Ford Coppola,"Robin Williams, Diane Lane, Brian Kerwin, Jenn...",uninformed country,NaN,1996,113 min,comedy,Robin Williams stars as a 10-year-old in a gro...,...,0,0,0,0,0,0,0,0,0,0
22988,Movie,12 Dates of Christmas,uninformed director,uninformed cast,uninformed country,NaN,2011,87 min,drama>romance,"Setup on a Christmas Eve date, a woman must re...",...,0,0,0,0,0,0,0,0,0,0
22989,Movie,10 Things I Hate About You,Gil Junger,"Heath Ledger, Julia Stiles, Joseph Gordon-Levi...",uninformed country,NaN,1999,97 min,comedy>drama>romance,"On the first day at his new school, Cameron in...",...,0,0,0,0,0,0,0,0,0,0

After looking at the number of duplicates movies there are, the next step was to look and see if they were on different streaming platforms. This will give a "true" duplicate.

In [87]:
df_movie_tv_streaming[df_movie_tv_streaming.duplicated(subset=['title', 'channel_streaming'], keep=False)]

Empty DataFrame
Columns: [movie_or_serie, title, director, cast, country, date_added_platform, release_year, duration_seconds, gender_type, description, channel_streaming, Unnamed: 0, action, actionadventure, adult, adventure, animals, animation, anime, anthology, arthouse, arts, biographical, black, british, buddy, cartoons, children, classic, classics, comedies, comedy, coming, concert, cooking, crime, cult, dance, documentaries, documentary, docuseries, drama, dramas, faith, family, fantasy, fitness, game, health, historical, history, horror, independent, international, kids, latino, lgbtq, lifestyle, military, music, musical, mystery, news, reality, romance, romantic, s, science, scifi, series, spanishlanguage, special, sports, st, suspense, talk, thriller, thrillers, unscripted, variety, western, young, -, competition, culture, disaster, entertainment, features, fiction, film, food, interest, korean, late, lgbtq+, musicals, mysteries, nature, of, parody, ...]
Index: []

[0 rows x 122 columns]

In [88]:
# verification of there being no duplicates for movies on the same streaming service multiple times in the dataset
df_movie_tv_streaming.loc[df_movie_tv_streaming['title']== 'Black Widow', 'channel_streaming']

74             disney-movies-and-tv-shows
16379    amazon-prime-movies-and-tv-shows
Name: channel_streaming, dtype: object

In [89]:
# check for missing values
df_movie_tv_streaming[df_movie_tv_streaming.isnull().any(axis=1)]

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
26,Movie,Marvel Studios’ 2021 Disney+ Day Special,uninformed director,uninformed cast,uninformed country,"November 12, 2021",2021,14 min,NaN,Marvel Studios’ Disney+ Day Special explores t...,...,0,0,0,0,0,0,0,0,0,0
30,Movie,Pixar 2021 Disney+ Day Special,uninformed director,"Pete Docter, Larry the Cable Guy, Jack Dylan G...",uninformed country,"November 12, 2021",2021,5 min,NaN,Join Pete Docter for a tour around Pixar and g...,...,0,0,0,0,0,0,0,0,0,0
339,Movie,Disney Holiday Magic Quest,uninformed director,uninformed cast,United States,"December 11, 2020",2020,46 min,NaN,ZOMBIES stars race to save the holiday magic!,...,0,0,0,0,0,0,0,0,0,0
1439,TV Show,Disney Kirby Buckets,uninformed director,"Jacob Bertrand, Mekai Curtis, Cade Sutton, Oli...",United States,NaN,2014,3 Seasons,actionadventure>comedy>coming>of>age,Welcome to Kirby's world! It's rude and sketchy.,...,0,0,0,0,0,0,0,0,0,0
1440,TV Show,Disney Mech-X4,uninformed director,"Nathaniel Potvin, Raymond Cham, Kamran Lucas, ...",Canada,NaN,2016,2 Seasons,actionadventure>comedy>science>fiction,Ryan discovers his ability to control a giant ...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaN,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,0,0,0,0,0,0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaN,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,0,0,0,0,0,0
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaN,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,0,0,0,0,0,0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaN,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,0,0,0,0,0,0
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaN,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,0,0,0,0,0,0

In [90]:
print('Mean of Numerical Columns')
print(df_movie_tv_streaming.mean(numeric_only=True))

Mean of Numerical Columns
release_year       2010.811244
Unnamed: 0            0.002609
action                0.140838
actionadventure       0.019654
adult                 0.005392
                      ...
spyespionage          0.000130
survival              0.000391
opera                 0.000087
travel                0.000043
melodrama             0.000087
Length: 112, dtype: float64

In [91]:
print('Median of Numerical Columns')
print(df_movie_tv_streaming.median(numeric_only=True))

Median of Numerical Columns
release_year       2016.0
Unnamed: 0            0.0
action                0.0
actionadventure       0.0
adult                 0.0
                    ...
spyespionage          0.0
survival              0.0
opera                 0.0
travel                0.0
melodrama             0.0
Length: 112, dtype: float64

In [92]:
print('Mode of Numerical Columns')
print(df_movie_tv_streaming.mode().iloc[0])

Mode of Numerical Columns
movie_or_serie                         Movie
title             10 Things I Hate About You
director                 uninformed director
cast                         uninformed cast
country                   uninformed country
                             ...
spyespionage                             0.0
survival                                 0.0
opera                                    0.0
travel                                   0.0
melodrama                                0.0
Name: 0, Length: 122, dtype: object

In [93]:
# making a duplicate df
df_movie_tv_stream = df_movie_tv_streaming.copy()

In [94]:
# creating a new csv
df_movie_tv_stream.to_csv("movie_tv_stream_v1.csv", index=False)

Conclusion

- This data is usable.

modify or correct the data in some way:
- Various rows are missing data but can be filled in with "uninformed" as many have already been filled in with.
- the duration_seconds column includes minutes and season number. This should be changed to "n/a" for tv seasons, and create a new column that is for tv season count. Also, this can be changed to minutes instead of seconds by removing the text in the row and changing it to a float/integer. 
- There doesn't appear to be any class imbalance.

Next Steps:
- missing data should be changed to be named "uninformed" to keep it similar across the dataset
- changing the duration_seconds column to duration_minutes and changing it to a float/int type (completed)
- creating a new column for number of tv seasons (completed)
- deeper analysis of release date versus added to the streaming service (this will be one of the )
- 0 and 1 streaming service column (?)

## additional cleaning
Now using the first version of the data, cleaning it up further for final analysis

In [95]:
df_streaming_tv_movie = pd.read_csv('movie_tv_stream_v1.csv')
df_streaming_tv_movie.sample(5)

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
11978,Movie,Paranormal Activity 3,uninformed director,uninformed cast,United States,"April 20, 2020",2011,84 min,horror>thriller,"In 1988, young sisters Katie and Kristi befrie...",...,0,0,0,0,0,0,0,0,0,0
9346,TV Show,Royal Pains,Jay Chandrasekhar,"Mark Feuerstein, Paulo Costanzo, Reshma Shetty...",United States,"May 18, 2017",2016,8 Seasons,comedies>dramas,Dr. Hank Lawson unexpectedly gets a career upg...,...,0,0,0,0,0,0,0,0,0,0
2950,Movie,Your Name Engraved Herein,Liu Kuang-hui,"Edward Chen, Tseng Ching-hua, Leon Dai, Jason ...",Taiwan,"December 23, 2020",2020,115 min,dramas>international>lgbtq,"In 1987, as martial law ends in Taiwan, Jia-ha...",...,0,0,0,0,0,0,0,0,0,0
3813,Movie,Wasp Network,Olivier Assayas,"Penélope Cruz, Edgar Ramírez, Wagner Moura, Ga...","France, Brazil, Spain, Belgium","June 19, 2020",2020,128 min,dramas>international>thrillers,Based on a true and gripping story: Cuban spie...,...,0,0,0,0,0,0,0,0,0,0
4451,TV Show,Playing with Fire,uninformed director,"Jason Day, Margarita Rosa de Francisco, Carlos...",United States,"January 22, 2020",2019,1 Season,international>s>romantic>s>spanishlanguage>s,Three prosperous women – including a mother an...,...,0,0,0,0,0,0,0,0,0,0

In [96]:
# stripping the white space
df_streaming_tv_movie['date_added_platform'] = df_streaming_tv_movie['date_added_platform'].str.strip()

In [97]:
# splitting data added platform into separate columns
df_streaming_tv_movie['date_added_platform'] = pd.to_datetime(df_streaming_tv_movie['date_added_platform'], format='%B %d, %Y')
df_streaming_tv_movie['month'] = df_streaming_tv_movie['date_added_platform'].dt.month.astype('Int64')
df_streaming_tv_movie['date'] = df_streaming_tv_movie['date_added_platform'].dt.day.astype('Int64')
df_streaming_tv_movie['year_added_platform'] = df_streaming_tv_movie['date_added_platform'].dt.year.astype('Int64')
df_streaming_tv_movie['month_name'] = df_streaming_tv_movie['date_added_platform'].dt.month_name()

In [98]:
df_streaming_tv_movie.sample(5)

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,soap,spyespionage,survival,opera,travel,melodrama,month,date,year_added_platform,month_name
20996,Movie,The Whistleblower,Larysa Kondracki,"Rachel Weisz, Vanessa Redgrave, Monica Bellucc...","Canada, Germany",NaT,2011,112 min,action>drama>suspense,This ripped-from-the-headlines thriller is ins...,...,0,0,0,0,0,0,<NA>,<NA>,<NA>,NaN
5426,TV Show,The Eagle of El-Se'eed,uninformed director,"Mohamed Ramadan, Sayed Rajab, Dorra Zarrouk, D...",uninformed country,2019-03-25,2018,1 Season,crime>s>international>s>action>adventure,A police officer and a drug lord become embroi...,...,0,0,0,0,0,0,3,25,2019,March
11968,Movie,In the Radiant City,uninformed director,uninformed cast,uninformed country,2020-05-01,2017,95 min,drama,A man returns to rural Kentucky where his fami...,...,0,0,0,0,0,0,5,1,2020,May
17750,TV Show,Beautiful Reborn Flower,uninformed director,"Lin Yun, Song Wei Long, Peter Ho",uninformed country,NaT,2020,1 Season,romance>suspense,"After his girlfriend Nan Sheng dies, He Ping m...",...,0,0,0,0,0,0,<NA>,<NA>,<NA>,NaN
10877,TV Show,Blindspotting,uninformed director,uninformed cast,uninformed country,2021-06-13,2021,1 Season,comedy>drama,"“Blindspotting” centers on Ashley, who is nipp...",...,0,0,0,0,0,0,6,13,2021,June

In [99]:
#create new season column
df_streaming_tv_movie['tv_season'] = np.nan

In [100]:
# check rows with 'season' in duration seconds column
season_mask = df_streaming_tv_movie['duration_seconds'].astype(str).str.contains('Season | Seasons', case=False, na=False)

# extract the number
df_streaming_tv_movie.loc[season_mask, 'tv_season'] = df_streaming_tv_movie.loc[season_mask, 'duration_seconds'].astype(str).str.extract('(\d+)')[0].astype(int)

# convert to int type
df_streaming_tv_movie['tv_season'] = pd.to_numeric(df_streaming_tv_movie['tv_season'], errors='coerce').astype('Int64')

In [101]:
# check rows with 'min' or 'mins' in duration seconds column
min_mask = df_streaming_tv_movie['duration_seconds'].astype(str).str.contains('min|mins', case=False, na=False)

# extract only the numbers and put them into its own column
df_streaming_tv_movie['runtime_minutes'] = np.nan
df_streaming_tv_movie.loc[min_mask, 'runtime_minutes'] = df_streaming_tv_movie.loc[min_mask, 'duration_seconds'].astype(str).str.extract('(\d+)')[0].astype('Int64')

In [102]:
# dropping some genre columns - unknown what they are for
df_streaming_tv_movie = df_streaming_tv_movie.drop(['s', 'st', 'of', '-'], axis=1)

In [103]:
df_streaming_tv_movie

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,survival,opera,travel,melodrama,month,date,year_added_platform,month_name,tv_season,runtime_minutes
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,2021-11-26,2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,11,26,2021,November,<NA>,23.0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,2021-11-26,1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,11,26,2021,November,<NA>,91.0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,11,26,2021,November,<NA>,23.0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,2021-11-26,2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,11,26,2021,November,<NA>,41.0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,2021-11-25,2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,11,25,2021,November,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaT,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,60.0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaT,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,4,NaN
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaT,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,90.0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaT,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,NaN
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaT,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,103.0

In [104]:
# Renaming columns
df_streaming_tv_movie = df_streaming_tv_movie.rename(columns={'month': 'month_added_platform'})
df_streaming_tv_movie = df_streaming_tv_movie.rename(columns={'date': 'day_added_platform'})
df_streaming_tv_movie = df_streaming_tv_movie.rename(columns={'movie_or_serie': 'movie_or_tv_show'})
df_streaming_tv_movie = df_streaming_tv_movie.rename(columns={'Unamed: 0': 'no_genre'})

# renaming streaming service in the 
df_streaming_tv_movie['channel_streaming'] = df_streaming_tv_movie['channel_streaming'].replace({
  'disney-movies-and-tv-shows': 'Disney',
  'netflix-shows' : 'Netflix',
  'amazon-prime-movies-and-tv-shows': 'Prime Video',
  'hulu-movies-and-tv-shows': 'Hulu'
})

In [105]:
df_streaming_tv_movie

,movie_or_tv_show,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,survival,opera,travel,melodrama,month_added_platform,day_added_platform,year_added_platform,month_name,tv_season,runtime_minutes
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,2021-11-26,2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,11,26,2021,November,<NA>,23.0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,2021-11-26,1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,11,26,2021,November,<NA>,91.0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,11,26,2021,November,<NA>,23.0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,2021-11-26,2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,11,26,2021,November,<NA>,41.0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,2021-11-25,2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,11,25,2021,November,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaT,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,60.0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaT,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,4,NaN
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaT,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,90.0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaT,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,NaN
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaT,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,103.0

In [106]:
# # creating a new csv for following weeks
df_streaming_tv_movie.to_csv("movie_tv_stream_v2.csv", index=False)
df_streaming_tv_movie

,movie_or_tv_show,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,survival,opera,travel,melodrama,month_added_platform,day_added_platform,year_added_platform,month_name,tv_season,runtime_minutes
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,2021-11-26,2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,11,26,2021,November,<NA>,23.0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,2021-11-26,1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,11,26,2021,November,<NA>,91.0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,11,26,2021,November,<NA>,23.0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,2021-11-26,2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,11,26,2021,November,<NA>,41.0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,2021-11-25,2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,11,25,2021,November,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaT,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,60.0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaT,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,4,NaN
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaT,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,90.0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaT,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,NaN
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaT,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,103.0

Wanting to do another angle of streaming difference by country, below is the making of a 3rd version CSV to onecoding the countries.

In [107]:
df_stream_countries = df_streaming_tv_movie.copy()
df_stream_countries

,movie_or_tv_show,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,survival,opera,travel,melodrama,month_added_platform,day_added_platform,year_added_platform,month_name,tv_season,runtime_minutes
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,2021-11-26,2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,11,26,2021,November,<NA>,23.0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,2021-11-26,1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,11,26,2021,November,<NA>,91.0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,11,26,2021,November,<NA>,23.0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,2021-11-26,2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,11,26,2021,November,<NA>,41.0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,2021-11-25,2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,11,25,2021,November,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaT,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,60.0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaT,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,4,NaN
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaT,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,90.0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaT,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,NaN
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaT,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,<NA>,<NA>,<NA>,NaN,<NA>,103.0

In [108]:
df_stream_countries = df_streaming_tv_movie.copy()
stream_countries_hb = df_stream_countries['country'].str.replace(', ', ',', regex=False).str.get_dummies(sep=',')
df_stream_countries = df_stream_countries.join(stream_countries_hb)

In [109]:
df_stream_countries

,movie_or_tv_show,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,United Arab Emirates,United Kingdom,United States,Uruguay,Vatican City,Venezuela,Vietnam,West Germany,Zimbabwe,uninformed country
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,2021-11-26,2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,0,0,0,0,0,1
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,2021-11-26,1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,0,0,0,0,0,1
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,2021-11-26,2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,1,0,0,0,0,0,0,0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,2021-11-26,2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,0,0,0,0,0,1
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,2021-11-25,2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaT,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,0,0,0,0,0,1
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaT,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,0,0,0,0,0,1
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaT,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,0,0,0,0,0,1
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaT,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,0,0,0,0,0,1
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaT,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,0,0,0,0,0,1

In [110]:
# creating a new csv v3
df_stream_countries.to_csv("movie_tv_stream_cv3.csv", index=False)

In [111]:
pd.Series(df_stream_countries.columns)

0        movie_or_tv_show
1                   title
2                director
3                    cast
4                 country
              ...
248             Venezuela
249               Vietnam
250          West Germany
251              Zimbabwe
252    uninformed country
Length: 253, dtype: object

# Movies Box office Dataset

Adding this post peer reviewed submission in order to clean the data and create a csv for the following weeks and the milestone.

In [112]:
df_box_office = pd.read_csv('enhanced_box_office_data.csv')
df_box_office

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,Vote_Count,Original_Language,Production_Countries
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126/10,6741.0,en,United States of America
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217/10,19032.0,en,"United Kingdom, United States of America"
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663/10,11403.0,en,United States of America
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.45/10,3944.0,en,"United Kingdom, United States of America"
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544/10,2530.0,en,United States of America
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,196,Devara Part 1,7361414.0,5600000.0,76.1,1761414.0,23.9,2024,"Action, Drama",7.0/10,30.0,te,India
4996,197,Kolpaçino 4 4'lük,7343114.0,0.0,0.0,7343114.0,100.0,2024,Comedy,4.0/10,4.0,tr,Turkey
4997,198,Lim Young Woong: Im Hero the Stadium,7305588.0,0.0,0.0,7305588.0,100.0,2024,"Music, Documentary",0.0/10,0.0,ko,South Korea
4998,199,Yolo,7241561.0,2001584.0,27.6,5239977.0,72.4,2024,"Drama, Comedy, Action",6.3/10,70.0,zh,China
4999,200,Sight,7206741.0,7206741.0,100.0,0.0,0.0,2024,"Drama, History",6.0/10,23.0,en,United States of America

In [113]:
df_box_office.describe()

,Rank,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Vote_Count
count,5000.00000,5.000000e+03,5.000000e+03,5000.000000,5.000000e+03,5000.000000,5000.000000,4830.000000
mean,100.50000,1.192137e+08,4.472523e+07,35.740620,7.448809e+07,64.256640,2012.000000,2531.585921
std,57.74008,2.005243e+08,7.727026e+07,30.656992,1.334932e+08,30.654531,7.211824,3946.272827
min,1.00000,1.666028e+06,0.000000e+00,0.000000,0.000000e+00,0.000000,2000.000000,0.000000
25%,50.75000,2.466220e+07,9.275150e+04,0.200000,1.371034e+07,42.200000,2006.000000,205.250000
50%,100.50000,4.844658e+07,1.798421e+07,37.050000,3.019444e+07,62.950000,2012.000000,1035.500000
75%,150.25000,1.197588e+08,5.386847e+07,57.800000,7.211578e+07,99.800000,2018.000000,3065.000000
max,200.00000,2.799439e+09,9.366622e+08,100.000000,1.993811e+09,100.000000,2024.000000,36753.000000

In [114]:
df_box_office.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rank                  5000 non-null   int64
 1   Release Group         5000 non-null   object
 2   $Worldwide            5000 non-null   float64
 3   $Domestic             5000 non-null   float64
 4   Domestic %            5000 non-null   float64
 5   $Foreign              5000 non-null   float64
 6   Foreign %             5000 non-null   float64
 7   Year                  5000 non-null   int64
 8   Genres                4822 non-null   object
 9   Rating                4830 non-null   object
 10  Vote_Count            4830 non-null   float64
 11  Original_Language     4830 non-null   object
 12  Production_Countries  4800 non-null   object
dtypes: float64(6), int64(2), object(5)
memory usage: 507.9+ KB

In [115]:
# encoding genres
one_hot_box_genre = df_box_office['Genres'].str.get_dummies(sep=', ')
one_hot_box_genre

,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4996,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
4998,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0

In [116]:
# made a copy of the data and added the encoding of genre
df_box_office_hb = df_box_office.copy()
df_box_office_hb = df_box_office_hb.join(one_hot_box_genre)
df_box_office_hb.describe()

,Rank,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Vote_Count,Action,Adventure,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
count,5000.00000,5.000000e+03,5.000000e+03,5000.000000,5.000000e+03,5000.000000,5000.000000,4830.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,100.50000,1.192137e+08,4.472523e+07,35.740620,7.448809e+07,64.256640,2012.000000,2531.585921,0.276800,0.212600,...,0.058600,0.087200,0.030400,0.086200,0.168800,0.102800,0.001400,0.212000,0.028800,0.006800
std,57.74008,2.005243e+08,7.727026e+07,30.656992,1.334932e+08,30.654531,7.211824,3946.272827,0.447462,0.409188,...,0.234898,0.282156,0.171702,0.280687,0.374613,0.303728,0.037394,0.408766,0.167261,0.082189
min,1.00000,1.666028e+06,0.000000e+00,0.000000,0.000000e+00,0.000000,2000.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50.75000,2.466220e+07,9.275150e+04,0.200000,1.371034e+07,42.200000,2006.000000,205.250000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,100.50000,4.844658e+07,1.798421e+07,37.050000,3.019444e+07,62.950000,2012.000000,1035.500000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,150.25000,1.197588e+08,5.386847e+07,57.800000,7.211578e+07,99.800000,2018.000000,3065.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,200.00000,2.799439e+09,9.366622e+08,100.000000,1.993811e+09,100.000000,2024.000000,36753.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [117]:
# removing the /10 of the rating to leave the rating and change it to a float
df_box_office_hb['Rating'] = df_box_office_hb['Rating'].str.replace('/10', '').astype(float)

In [118]:
df_box_office_hb

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126,...,0,0,0,0,0,0,0,1,0,0
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217,...,0,0,0,0,0,0,0,0,0,0
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663,...,0,0,0,0,0,0,0,0,0,0
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.450,...,0,0,0,0,1,0,0,0,0,0
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,196,Devara Part 1,7361414.0,5600000.0,76.1,1761414.0,23.9,2024,"Action, Drama",7.000,...,0,0,0,0,0,0,0,0,0,0
4996,197,Kolpaçino 4 4'lük,7343114.0,0.0,0.0,7343114.0,100.0,2024,Comedy,4.000,...,0,0,0,0,0,0,0,0,0,0
4997,198,Lim Young Woong: Im Hero the Stadium,7305588.0,0.0,0.0,7305588.0,100.0,2024,"Music, Documentary",0.000,...,0,0,1,0,0,0,0,0,0,0
4998,199,Yolo,7241561.0,2001584.0,27.6,5239977.0,72.4,2024,"Drama, Comedy, Action",6.300,...,0,0,0,0,0,0,0,0,0,0
4999,200,Sight,7206741.0,7206741.0,100.0,0.0,0.0,2024,"Drama, History",6.000,...,1,0,0,0,0,0,0,0,0,0

In [119]:
# Changing the type of the Vote Count to an integer
df_box_office_hb['Vote_Count'] = df_box_office_hb['Vote_Count'].astype('Int64')

In [120]:
# Creating a final cleaned CSV
df_box_office_hb.to_csv("movie_box_office_v1.csv", index=False)

Below is the creation of the 2nd version of the csv which will be encoding the Production Countries

In [121]:
df_boxoffice_country = df_box_office_hb.copy()

In [122]:
boxoffice_country_hb = df_boxoffice_country['Production_Countries'].str.replace(', ', ',').str.get_dummies(sep=',')
df_boxoffice_country = df_boxoffice_country.join(boxoffice_country_hb)

In [123]:
df_boxoffice_country

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,...,Taiwan,Thailand,Tunisia,Turkey,Ukraine,United Arab Emirates,United Kingdom,United States of America,Vietnam,Yugoslavia
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126,...,0,0,0,0,0,0,0,1,0,0
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217,...,0,0,0,0,0,0,1,1,0,0
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663,...,0,0,0,0,0,0,0,1,0,0
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.450,...,0,0,0,0,0,0,1,1,0,0
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,196,Devara Part 1,7361414.0,5600000.0,76.1,1761414.0,23.9,2024,"Action, Drama",7.000,...,0,0,0,0,0,0,0,0,0,0
4996,197,Kolpaçino 4 4'lük,7343114.0,0.0,0.0,7343114.0,100.0,2024,Comedy,4.000,...,0,0,0,1,0,0,0,0,0,0
4997,198,Lim Young Woong: Im Hero the Stadium,7305588.0,0.0,0.0,7305588.0,100.0,2024,"Music, Documentary",0.000,...,0,0,0,0,0,0,0,0,0,0
4998,199,Yolo,7241561.0,2001584.0,27.6,5239977.0,72.4,2024,"Drama, Comedy, Action",6.300,...,0,0,0,0,0,0,0,0,0,0
4999,200,Sight,7206741.0,7206741.0,100.0,0.0,0.0,2024,"Drama, History",6.000,...,0,0,0,0,0,0,0,1,0,0

In [124]:
pd.Series(df_boxoffice_country.columns)

0                          Rank
1                 Release Group
2                    $Worldwide
3                     $Domestic
4                    Domestic %
                 ...
103        United Arab Emirates
104              United Kingdom
105    United States of America
106                     Vietnam
107                  Yugoslavia
Length: 108, dtype: object

In [125]:
# creating a new csv v2
df_boxoffice_country.to_csv("movie_box_office_cv2.csv", index=False)

# 4. Storytelling With Data graph

Just like last week: choose any graph in the Introduction of Storytelling With Data (p. 1-17). Use matplotlib to reproduce it in a rough way. I don't expect you to spend an enormous amount of time on this; I understand that you likely will not have time to re-create every feature of the graph. However, if you're excited about learning to use matplotlib, this is a good way to do that. You don't have to duplicate the exact values on the graph; just the same rough shape will be enough.  If you don't feel comfortable using matplotlib yet, do the best you can and write down what you tried or what Google searches you did to find the answers.

In [ ]:
import matplotlib.pyplot as plt

df_tickets = pd.DataFrame({"received": [160, 184, 241, 149, 180, 161, 132, 202, 160, 139, 149, 177],
                           "processed": [160, 184, 237, 148, 181, 150, 123, 156, 126, 104, 124, 140],
                           "month": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]})

plt.plot(df_tickets["month"], df_tickets["received"], label="Tickets Received", marker='o')
plt.plot(df_tickets["month"], df_tickets["processed"], label="Tickets Processed", marker='o')
plt.legend()
plt.xlabel("Month")
plt.ylabel("Number of Tickets")
plt.xticks(rotation=45)
plt.title("Ticket volume over time")
plt.grid()